### ISSUE TITLE
Question: Need clarification on version requirement. It this plugin for 4.x generally (4.0 & 4.1)? Or is it exclusive to 4.2+ only?

### ISSUE THREAD

**Issue by BurntAussieTyre** [QueenOfSquiggles/squiggles-fur#1]

**Comment by QueenOfSquiggles** [comment]
Oh yeah! Sorry I wasn't super clear. I technically developed this addon on Godot 4.2-beta3, but I do not believe that I used any features specific to 4.2 to develop it so it likely works for 4.0 and 4.1 latest. But I'll double check and add some clarity to the readme before closing this issue

**Comment by QueenOfSquiggles** [comment]
Alright! As of #2 , this addon supports all currently available 4.X Godot versions. With the only quirk being that 4.0 doesn't have the thing I used to mark the scene as unsaved, so closing out of a scene without saving your changes will not produce a warning. But that is only specifically in the case of mesh instancing, which is generally done once and never again unless you are adjusting the style. Marking this as closed. Please open another issue if you run into any troubles! Thanks for pointing this out to me!!!!
